name: build
on:
  pull_request:
    branches:
      - 'master'
      - 'dev'
    types: [opened, reopened, edited, synchronize]
    paths:
      - 'index.js'
      - 'test/**'
      - 'package.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Test
      run: npm test
  # *** Can use this job instead when tests are properly in place and REPORTER_ID has been added to the repository secrets 
  # coverage:
    # runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v2
    # - name: Install dependencies
    #   run: npm i
    # - name: Generate coverage report
    #   run: npm run coverage
    # - name: Upload report to Code Climate
    #   uses: kaskadi/action-cc-reporter@master
    #   env:
    #     CC_TEST_REPORTER_ID: ${{ secrets.REPORTER_ID }}
    #     GIT_BRANCH: ${{ github.base_ref }}
    #     GIT_COMMIT: ${{ github.sha }}